<?php
/**
 * Bounded compatibility localization for the WordPress AI plugin admin UI.
 *
 * @package NpcinkCloudAddon
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Npcink_Cloud_AI_Plugin_Localization' ) ) {
	/**
	 * Provides a narrow zh_CN compatibility layer for high-traffic AI plugin UI strings.
	 */
	final class Npcink_Cloud_AI_Plugin_Localization {
		private const AI_TEXT_DOMAIN = 'ai';

		/**
		 * Registers admin-only localization hooks.
		 *
		 * @return void
		 */
		public static function register(): void {
			add_filter( 'gettext', array( __CLASS__, 'filter_gettext' ), 20, 3 );
			add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_script_locale_data' ), 1 );
			add_action( 'enqueue_block_editor_assets', array( __CLASS__, 'enqueue_script_locale_data' ), 1 );
		}

		/**
		 * Translates selected AI plugin PHP strings when no upstream zh_CN language pack is present.
		 *
		 * @param string $translation Existing translation.
		 * @param string $text Original English string.
		 * @param string $domain Text domain.
		 * @return string
		 */
		public static function filter_gettext( string $translation, string $text, string $domain ): string {
			if ( self::AI_TEXT_DOMAIN !== $domain || ! self::should_localize() ) {
				return $translation;
			}

			$translations = self::translations();

			return $translations[ $text ] ?? $translation;
		}

		/**
		 * Adds JS locale data for AI plugin React/admin screens.
		 *
		 * @return void
		 */
		public static function enqueue_script_locale_data(): void {
			if ( ! self::should_localize() || ! function_exists( 'wp_enqueue_script' ) || ! function_exists( 'wp_localize_script' ) ) {
				return;
			}

			$locale_data = array(
				'' => array(
					'domain' => self::AI_TEXT_DOMAIN,
					'lang'   => 'zh_CN',
				),
			);
			foreach ( self::translations() as $source => $translation ) {
				$locale_data[ $source ] = array( $translation );
			}

			$handle = 'npcink-cloud-addon-ai-plugin-localization';
			wp_enqueue_script(
				$handle,
				plugins_url( 'assets/ai-plugin-localization.js', NPCINK_CLOUD_ADDON_FILE ),
				array( 'wp-i18n' ),
				NPCINK_CLOUD_ADDON_VERSION,
				true
			);
			wp_localize_script(
				$handle,
				'NpcinkCloudAiPluginLocalization',
				array( 'localeData' => $locale_data )
			);
		}

		/**
		 * Returns whether the compatibility translations should run.
		 *
		 * @return bool
		 */
		public static function should_localize(): bool {
			if ( function_exists( 'is_admin' ) && ! is_admin() ) {
				return false;
			}

			$locale = '';
			if ( function_exists( 'determine_locale' ) ) {
				$locale = (string) determine_locale();
			} elseif ( function_exists( 'get_user_locale' ) ) {
				$locale = (string) get_user_locale();
			} elseif ( function_exists( 'get_locale' ) ) {
				$locale = (string) get_locale();
			}

			if ( '' === $locale ) {
				return false;
			}

			return 0 === strpos( str_replace( '-', '_', strtolower( $locale ) ), 'zh_' );
		}

		/**
		 * Returns the fixed AI plugin translation map.
		 *
		 * @return array<string,string>
		 */
		public static function translations(): array {
			return array(
				'AI' => 'AI',
				'Configure AI features and experiments for your WordPress site.' => '配置此 WordPress 站点的 AI 功能和实验功能。',
				'Enable AI' => '启用 AI',
				'AI Plugin initialization failed: %s' => 'AI 插件初始化失败：%s',
				'AI client is not available.' => 'AI 客户端不可用。',
				'AI plugin cannot run due to the following issues:' => 'AI 插件因以下问题无法运行：',
				'AI settings page render function not found. Run npm run build:routes to generate build assets.' => '未找到 AI 设置页面渲染函数。请运行 npm run build:routes 生成构建资源。',
				'Docs' => '文档',
				'Contribute' => '参与贡献',
				'Developer Tools' => '开发者工具',
				'Model selection' => '模型选择',
				'Select a specific provider and model per feature' => '为每个功能选择指定的提供方和模型',
				'Control whether AI is enabled for your site. When disabled, all features and experiments will be inactive regardless of their individual settings.' => '控制此站点是否启用 AI。关闭后，即使单个功能已启用，所有功能和实验功能也会停用。',
				'Editor Experiments' => '编辑器实验功能',
				'AI-powered experiments for the block editor, including content generation and enhancement tools.' => '面向区块编辑器的 AI 实验功能，包括内容生成和增强工具。',
				'Type-ahead Text' => '输入预测文本',
				'Ghost text suggestions while writing paragraphs in the block editor. Requires an AI connector that includes support for text generation models.' => '在区块编辑器中撰写段落时显示灰色文本建议。需要支持文本生成模型的 AI 连接器。',
				'Admin Experiments' => '后台实验功能',
				'AI-powered experiments for the WordPress admin area, including exploration and testing tools.' => '面向 WordPress 后台的 AI 实验功能，包括探索和测试工具。',
				'Abilities Explorer' => '能力浏览器',
				'Discover, inspect, test, and document all abilities registered via the WordPress Abilities API.' => '发现、检查、测试并记录通过 WordPress Abilities API 注册的所有能力。',
				'Connector Approval' => '连接器审批',
				'Connector Approvals' => '连接器审批',
				'Require explicit administrator approval before plugins or themes can use AI connectors configured on this site. Note this is an experimental, proof-of-concept feature and as such, issues may be encountered. Feedback welcome and desired to help shape the feature.' => '插件或主题使用本站配置的 AI 连接器前，需要管理员明确审批。此功能仍是实验性概念验证，可能会遇到问题，欢迎反馈以帮助完善。',
				'AI Request Logging' => 'AI 请求日志',
				'AI Request Logs' => 'AI 请求日志',
				'Logs AI requests for observability and debugging. View detailed logs under Tools.' => '记录 AI 请求，用于观测和调试。可在“工具”下查看详细日志。',
				'Key Encryption' => '密钥加密',
				'Encrypts AI provider API keys at rest using bundled libsodium encryption. Keys are transparently decrypted on read and re-encrypted on write. Disabling the experiment or deactivating the plugin restores plaintext keys.' => '使用内置 libsodium 加密静态存储的 AI 提供方 API 密钥。读取时会透明解密，写入时会重新加密。停用此实验功能或停用插件会恢复明文密钥。',
				'Detailed logs of every AI request made by the WordPress AI plugin.' => '记录 WordPress AI 插件发起的每一次 AI 请求的详细日志。',
				'AI Capabilities' => 'AI 能力',
				'AI Status' => 'AI 状态',
				'API Key Settings' => 'API 密钥设置',
				'Approval matrix' => '审批矩阵',
				'Approve' => '批准',
				'Asset file for "%1$s" is invalid and cannot be registered.' => '“%1$s”的资源文件无效，无法注册。',
				'Asset file for "%1$s" is missing and cannot be registered.' => '缺少“%1$s”的资源文件，无法注册。',
				'Attempts' => '尝试次数',
				'Caller' => '调用方',
				'Connector' => '连接器',
				'Connectors' => '连接器',
				'Context' => '上下文',
				'Control which plugins and themes are allowed to use each AI connector on this site. Prompts from unapproved callers are prevented and listed below for review.' => '控制哪些插件和主题可以使用本站的每个 AI 连接器。未获批准调用方的提示会被阻止，并在下方列出以供审核。',
				'Copy Log ID' => '复制日志 ID',
				'Duration' => '耗时',
				'Edit %s (has errors)' => '编辑 %s（有错误）',
				'Failed' => '失败',
				'Failed to dismiss request.' => '忽略请求失败。',
				'Failed to load approval data.' => '加载审批数据失败。',
				'Failed to load providers.' => '加载提供方失败。',
				'Failed to save developer settings.' => '保存开发者设置失败。',
				'Failed to update approval.' => '更新审批失败。',
				'Filter by AI provider.' => '按 AI 提供方筛选。',
				'Filter by log type.' => '按日志类型筛选。',
				'Filter by status.' => '按状态筛选。',
				'Filter by user ID.' => '按用户 ID 筛选。',
				'General' => '常规',
				'Generated image output' => '生成的图片输出',
				'Generated image output (base64)' => '生成的图片输出（base64）',
				'Generated Images' => '生成的图片',
				'Image Generation' => '图片生成',
				'Image %d' => '图片 %d',
				'Input Preview' => '输入预览',
				'Input Tokens' => '输入 Token',
				'Log entry not found.' => '未找到日志条目。',
				'Log ID copied to clipboard.' => '日志 ID 已复制到剪贴板。',
				'Output Preview' => '输出预览',
				'Output Tokens' => '输出 Token',
				'Provider & Model' => '提供方和模型',
				'Provider / Model' => '提供方 / 模型',
				'Request Details' => '请求详情',
				'Request Kind' => '请求类型',
				'Refresh' => '刷新',
				'Review requests' => '查看请求',
				'Search in operations, request previews, response previews, and error messages.' => '在操作、请求预览、响应预览和错误信息中搜索。',
				'Status' => '状态',
				'Successfully purged %d log entries.' => '已成功清除 %d 条日志。',
				'Time' => '时间',
				'Time period' => '时间范围',
				'Timestamp' => '时间戳',
				'Tokens per Second' => '每秒 Token',
				'Token Usage' => 'Token 用量',
				'Total Tokens' => '总 Token',
				'Source' => '来源',
				'Source File' => '来源文件',
				'User' => '用户',
				'User ID' => '用户 ID',
				'View details' => '查看详情',
				'WordPress AI' => 'WordPress AI',
				'WordPress Core' => 'WordPress 核心',
				'%d plugin or theme is requesting access to an AI connector.' => '%d 个插件或主题正在请求访问 AI 连接器。',
				'%d plugins or themes are requesting access to AI connectors.' => '%d 个插件或主题正在请求访问 AI 连接器。',
				'%d ms' => '%d 毫秒',
				'%s/s' => '%s/秒',
				'< 100 tokens' => '少于 100 Token',
				'< 500 tokens' => '少于 500 Token',
				'< 1K tokens' => '少于 1K Token',
				'< 5K tokens' => '少于 5K Token',
				'> 1K tokens' => '超过 1K Token',
				'> 5K tokens' => '超过 5K Token',
				'> 10K tokens' => '超过 10K Token',
				'Allow %1$s to use %2$s' => '允许 %1$s 使用 %2$s',
				'The "%1$s" AI connector has not been approved for use by "%2$s".' => '“%1$s” AI 连接器尚未获准供“%2$s”使用。',
				'Cloud' => '云端',
				'Chat History' => '聊天历史',
				'Configure an AI provider' => '配置 AI 提供方',
				'Embedding Generation' => '嵌入生成',
				'Enable a feature or experiment' => '启用功能或实验',
				'Globally enable AI Features' => '全局启用 AI 功能',
				'Has Tokens (> 0)' => '有 Token（> 0）',
				'Last seen' => '上次出现',
				'Local' => '本地',
				'Model' => '模型',
				'Music Generation' => '音乐生成',
				'No AI connectors are currently registered. Configure a connector first.' => '当前没有已注册的 AI 连接器。请先配置连接器。',
				'No plugins or themes are currently waiting for AI access.' => '目前没有插件或主题等待 AI 访问授权。',
				'No pending approval request matches the provided key.' => '没有与所提供密钥匹配的待审批请求。',
				'No Tokens' => '无 Token',
				'Operation' => '操作',
				'Other' => '其他',
				'Pending requests' => '待处理请求',
				'PHP version %1$s or higher is required. You are running PHP version %2$s.' => '需要 PHP %1$s 或更高版本。当前运行的是 PHP %2$s。',
				'Plugin basename and connector ID are required.' => '插件 basename 和连接器 ID 为必填项。',
				'Speech Generation' => '语音生成',
				'Settings' => '设置',
				'Text Generation' => '文本生成',
				'Text to Speech' => '文本转语音',
				'Token Range' => 'Token 范围',
				'Type' => '类型',
				'Unable to load filter metadata.' => '无法加载筛选元数据。',
				'Unsupported capability: %s' => '不支持的能力：%s',
				'Video Generation' => '视频生成',
				'WordPress version %s or higher is required.' => '需要 WordPress %s 或更高版本。',
				'You do not have sufficient permissions to access this page.' => '你没有足够权限访问此页面。',
				'Your WordPress environment has AI functionality disabled. The AI plugin will not work until AI support is enabled.' => '当前 WordPress 环境已禁用 AI 功能。启用 AI 支持前，AI 插件无法工作。',
				'Last Minute' => '最近 1 分钟',
				'Last Hour' => '最近 1 小时',
				'Last 24 Hours' => '最近 24 小时',
				'Last 7 Days' => '最近 7 天',
				'Last 30 Days' => '最近 30 天',
				'All Time' => '全部时间',
				'Requests' => '请求',
				'Tokens' => 'Token',
				'Avg Time' => '平均耗时',
				'Success Rate' => '成功率',
				'Manage Logs' => '管理日志',
				'Danger Zone' => '危险操作区',
				'Permanently delete all logged requests. This action cannot be undone.' => '永久删除所有已记录的请求。此操作无法撤销。',
				'%d Item selected' => '已选择 %d 项',
				'%d Items selected' => '已选择 %d 项',
				'Purge All Logs' => '清空所有日志',
				'Are you sure?' => '确定吗？',
				'Yes, Purge All' => '是，全部清空',
				'All logs have been purged.' => '所有日志已清空。',
				'Unable to load summary data.' => '无法加载汇总数据。',
				'Something went wrong. Please try again.' => '出现问题，请重试。',
				'Dismiss' => '忽略',
				'Comment Moderation' => '评论审核',
				'Automatically moderate comments based on toxicity detection and sentiment analysis. Requires an AI connector that includes support for text generation models.' => '基于毒性检测和情绪分析自动审核评论。需要支持文本生成模型的 AI 连接器。',
				'Automatically moderate guest comments' => '自动审核访客评论',
				'%d comment queued for analysis.' => '%d 条评论已加入分析队列。',
				'%d comments queued for analysis.' => '%d 条评论已加入分析队列。',
				'All Sentiments' => '所有情绪',
				'All Toxicities' => '所有毒性级别',
				'Analyze Sentiment and Toxicity' => '分析情绪和毒性',
				'Analyze this comment' => '分析此评论',
				'Analyzing…' => '正在分析…',
				'Comment Analysis' => '评论分析',
				'Filter by Sentiment' => '按情绪筛选',
				'Filter by Toxicity' => '按毒性筛选',
				'High' => '高',
				'High Toxicity (>=70%)' => '高毒性（>=70%）',
				'Low' => '低',
				'Low Toxicity (<40%)' => '低毒性（<40%）',
				'Medium' => '中',
				'Medium Toxicity (40%-69%)' => '中等毒性（40%-69%）',
				'Negative' => '负面',
				'Neutral' => '中性',
				'Positive' => '正面',
				'Queued' => '已排队',
				'Sentiment' => '情绪',
				'Settings → Connectors' => '设置 → 连接器',
				'Toxicity' => '毒性',
				'Other Features' => '其他功能',
				'Additional AI-powered features.' => '其他 AI 功能。',
				'Enable all' => '全部启用',
				'Disable all' => '全部停用',
				'Settings saved.' => '设置已保存。',
				'AI enabled.' => 'AI 已启用。',
				'AI disabled.' => 'AI 已停用。',
				'Failed to save settings.' => '设置保存失败。',
				'Save' => '保存',
				'Save %s settings' => '保存 %s 设置',
				'Saving settings…' => '正在保存设置…',
				'%d field needs attention' => '%d 个字段需要处理',
				'%d fields need attention' => '%d 个字段需要处理',
				'%s enabled.' => '%s 已启用。',
				'%s disabled.' => '%s 已停用。',
				'%s settings saved.' => '%s 设置已保存。',
				'More information' => '更多信息',
				'Manage Connectors' => '管理连接器',
				'Reset to default' => '重置为默认值',
				'— Default —' => '— 默认 —',
				'The AI plugin requires a valid AI Connector to function properly. Please review the AI Connectors you have configured to ensure they are valid.' => 'AI 插件需要有效的 AI 连接器才能正常工作。请检查已配置的 AI 连接器，确保它们有效。',
				'The AI plugin requires a valid AI Connector to function properly. Verify you have one or more AI Connectors configured.' => 'AI 插件需要有效的 AI 连接器才能正常工作。请确认已配置一个或多个 AI 连接器。',
				'The plugin assets are not built. This is most likely because you downloaded the plugin from the GitHub repository without building the assets. Please run `nvm use && npm ci && npm run build` to build the assets.' => '插件资源尚未构建。这很可能是因为你从 GitHub 仓库下载了插件但未构建资源。请运行 `nvm use && npm ci && npm run build` 来构建资源。',
				'The previously selected provider is no longer available. This feature will not function as expected until a valid provider is selected or the selection is reset to default.' => '先前选择的提供方已不可用。此功能在选择有效提供方或重置为默认值之前可能无法正常工作。',
				'This feature does not require an AI provider or model.' => '此功能不需要 AI 提供方或模型。',
				'Content Classification' => '内容分类',
				'AI-powered suggestions for post tags and categories based on content analysis. Requires an AI connector that includes support for text generation models.' => '基于内容分析，为文章标签和分类目录提供 AI 建议。需要支持文本生成模型的 AI 连接器。',
				'Taxonomy Strategy' => '分类策略',
				'Taxonomy strategy' => '分类策略',
				'TAXONOMY STRATEGY' => '分类策略',
				'Suggest new terms based on context' => '根据上下文建议新术语',
				'Use existing terms only' => '仅使用现有术语',
				'Only suggest existing terms' => '仅建议现有术语',
				'Maximum Suggestions' => '最大建议数量',
				'Maximum suggestions' => '最大建议数量',
				'MAXIMUM SUGGESTIONS' => '最大建议数量',
				'Suggest %s' => '建议%s',
				'Add more content to enable AI suggestions (approximately 150 words).' => '请添加更多内容以启用 AI 建议（约 150 个词）。',
				'Content Classification will be available when the post content has at least %d characters.' => '文章内容至少达到 %d 个字符后可使用内容分类建议。',
				'Add "%s"' => '添加“%s”',
				'Dismiss "%s"' => '忽略“%s”',
				'Dismiss all' => '全部忽略',
				'Suggest again' => '重新建议',
				'Suggested %s' => '建议的%s',
				'new' => '新建',
				'Content Resizing' => '内容改写长度',
				'Shorten, expand, or rephrase selected block content. Requires an AI connector that includes support for text generation models.' => '缩短、扩展或改写选中的区块内容。需要支持文本生成模型的 AI 连接器。',
				'Resize Content' => '调整内容长度',
				'Shorten' => '缩短',
				'Expand' => '扩展',
				'Rephrase' => '改写',
				'Accept' => '接受',
				'Regenerate' => '重新生成',
				'Original' => '原文',
				'Original content' => '原始内容',
				'Suggested' => '建议',
				'Suggested content' => '建议内容',
				'Suggested replacement' => '建议替换内容',
				'No change' => '无变化',
				'No change in word count' => '字数无变化',
				'+%d word' => '+%d 个词',
				'+%d words' => '+%d 个词',
				'Text is too short to shorten further.' => '文本太短，无法继续缩短。',
				'An error occurred while resizing content.' => '调整内容时发生错误。',
				'Excerpt Generation' => '文章摘要生成',
				'Generates excerpt suggestions from content. Requires an AI connector that includes support for text generation models.' => '根据内容生成文章摘要建议。需要支持文本生成模型的 AI 连接器。',
				'Generate excerpt' => '生成文章摘要',
				'Regenerate excerpt' => '重新生成文章摘要',
				'Failed to generate excerpt.' => '生成文章摘要失败。',
				'Excerpt generation will be available when the post content has at least %d characters.' => '文章内容至少达到 %d 个字符后可生成文章摘要。',
				'Alt Text Generation' => '替代文本生成',
				'Generates accessible alternative (alt) text for images using AI vision models, following common web accessibility guidance. Requires an AI connector that includes support for vision-based image analysis models.' => '使用 AI 视觉模型为图片生成符合常见无障碍规范的替代文本。需要支持视觉图片分析模型的 AI 连接器。',
				'Generate Alt Text' => '生成替代文本',
				'Alt Text' => '替代文本',
				'Alt text' => '替代文本',
				'Generated Alt Text' => '已生成替代文本',
				'Regenerate Alt Text' => '重新生成替代文本',
				'Generating alt text…' => '正在生成替代文本…',
				'Generating alt text: %1$d / %2$d…' => '正在生成替代文本：%1$d/%2$d…',
				'Alt text generated and applied.' => '替代文本已生成并应用。',
				'Alt text generated for %d image.' => '已为 %d 张图片生成替代文本。',
				'Alt text generated for all %d images.' => '已为全部 %d 张图片生成替代文本。',
				'Alt text generated for %1$d of %2$d images. Failed attachment IDs: %3$s.' => '已为 %1$d/%2$d 张图片生成替代文本。失败的附件 ID：%3$s。',
				'Image identified as decorative. Alt text cleared.' => '图片已识别为装饰性图片，替代文本已清空。',
				'No image available to generate alt text for.' => '没有可用于生成替代文本的图片。',
				'An error occurred while generating alt text.' => '生成替代文本时发生错误。',
				'An unexpected error occurred while generating alt text.' => '生成替代文本时发生意外错误。',
				'Failed to generate alt text.' => '生成替代文本失败。',
				'This image appears to be decorative. Applying will set an empty alt attribute, which tells screen readers to skip it.' => '这张图片似乎是装饰性图片。应用后会设置空的 alt 属性，提示屏幕阅读器跳过它。',
				'Dismiss this notice.' => '忽略此通知。',
				'Meta Description Generation' => 'SEO 描述生成',
				'Generates meta description suggestions and integrates those with various SEO plugins. Requires an AI connector that includes support for text generation models.' => '生成 SEO 描述建议，并与多种 SEO 插件集成。需要支持文本生成模型的 AI 连接器。',
				'Meta description' => 'SEO 描述',
				'%d characters' => '%d 个字符',
				'Aim for 140–160 characters for optimal display in search results.' => '建议控制在 140–160 个字符，以便在搜索结果中最佳展示。',
				'Copy to clipboard' => '复制到剪贴板',
				'Edit description' => '编辑描述',
				'Regenerate meta description' => '重新生成 SEO 描述',
				'No meta description suggestion was generated.' => '未生成 SEO 描述建议。',
				'Failed to generate meta description.' => '生成 SEO 描述失败。',
				'Meta description copied to clipboard.' => 'SEO 描述已复制到剪贴板。',
				'Meta Description generation will be available when the post content has at least %d characters.' => '文章内容至少达到 %d 个字符后可生成 SEO 描述。',
				'Editorial Notes' => '编辑建议',
				'Adds editorial suggestions to posts block-by-block, covering Accessibility, Readability, Grammar, and SEO. Requires an AI connector that includes support for text generation models.' => '按区块为文章添加编辑建议，覆盖无障碍、可读性、语法和 SEO。需要支持文本生成模型的 AI 连接器。',
				'Generate Editorial Note' => '生成编辑建议',
				'%d suggestion added.' => '已添加 %d 条建议。',
				'%d suggestions added.' => '已添加 %d 条建议。',
				'No new suggestions found.' => '未找到新建议。',
				'Editorial Notes will be available when the post content has at least %d characters.' => '文章内容至少达到 %d 个字符后可生成编辑建议。',
				'Reviewing…' => '正在检查…',
				'Reviewing blocks… (%1$d of %2$d)' => '正在检查区块…（%1$d/%2$d）',
				'Editorial Updates' => '编辑更新',
				'Applies pending editorial Notes to your content automatically. Requires an AI connector that includes support for text generation models.' => '自动将待处理的编辑建议应用到内容中。需要支持文本生成模型的 AI 连接器。',
				'Apply Editorial Updates' => '应用编辑更新',
				'Automatically applies pending editorial Notes to update your content.' => '自动应用待处理的编辑建议来更新内容。',
				'No pending Notes found to refine.' => '未找到待应用的编辑建议。',
				'No blocks found matching the existing Notes.' => '未找到与现有建议匹配的区块。',
				'No content changes were needed based on the existing Notes.' => '根据现有建议无需更改内容。',
				'%d block refined with AI.' => '已用 AI 优化 %d 个区块。',
				'%d blocks refined with AI.' => '已用 AI 优化 %d 个区块。',
				'Refining block (%1$s of %2$s)…' => '正在优化区块（%1$s/%2$s）…',
				'Refinement failed for all blocks.' => '所有区块优化均失败。',
				'Review in Revisions' => '在修订版本中查看',
				'Content Summarization' => '内容总结',
				'Summarizes long-form content into digestible overviews. Requires an AI connector that includes support for text generation models.' => '将长内容总结为易读的概览。需要支持文本生成模型的 AI 连接器。',
				'Generate Summary' => '生成摘要区块',
				'This will create a block that is a summary of the content of this post.' => '这将创建一个区块，作为本文内容的摘要。',
				'Content Summary' => '内容总结',
				'A generated summary of the post content.' => '根据文章内容生成的总结。',
				'Regenerate Summary' => '重新生成摘要区块',
				'This will update the generated summary block with a new summary of the content of this post.' => '这会用本文内容的新摘要更新已生成的摘要区块。',
				'Invalid response from API.' => 'API 返回无效响应。',
				'Failed to generate summary.' => '生成摘要区块失败。',
				'Summarization will be available when the post content has at least %d characters.' => '文章内容至少达到 %d 个字符后可使用内容总结。',
				'Title Generation' => '标题生成',
				'Generates title suggestions from content. Requires an AI connector that includes support for text generation models.' => '根据内容生成标题建议。需要支持文本生成模型的 AI 连接器。',
				'Title suggestion' => '标题建议',
				'Generated title' => '已生成标题',
				'Insert' => '插入',
				'Review, edit and insert the suggested title or regenerate a new one.' => '查看、编辑并插入建议标题，或重新生成一个。',
				'No title suggestion was generated.' => '未生成标题建议。',
				'Failed to generate title.' => '生成标题失败。',
				'This feature requires an AI Connector to function properly.' => '此功能需要 AI 连接器才能正常工作。',
				'This feature requires an AI Connector to function properly. Please set up a provider in Settings → Connectors.' => '此功能需要 AI 连接器才能正常工作。请在“设置 → 连接器”中设置提供方。',
				'This feature requires a valid AI Connector to function properly. Please set up a provider to use this feature in Settings → Connectors.' => '此功能需要有效的 AI 连接器才能正常工作。请在“设置 → 连接器”中设置提供方。',
				'This feature requires a valid AI Connector to function properly. Please set up a provider to use this feature in %s.' => '此功能需要有效的 AI 连接器才能正常工作。请在 %s 中设置提供方。',
				'Base64 Image Import' => 'Base64 图片导入',
				'Image Generation and Editing' => '图片生成与编辑',
				'Image Prompt Generation' => '图片提示词生成',
				'Generate and edit images using AI. Requires an AI connector that includes support for image generation models.' => '使用 AI 生成和编辑图片。需要支持图片生成模型的 AI 连接器。',
				'Generate Editorial Notes' => '生成编辑建议',
				'This analyzes the content of this post block-by-block and adds editorial Notes with suggestions on each block.' => '这会逐个区块分析本文内容，并为每个区块添加编辑建议。',
				'Meta Description' => 'SEO 描述',
				'Generate Meta Description' => '生成 SEO 描述',
				'Generate Image' => '生成图片',
				'Describe the image you want to generate.' => '描述你想生成的图片。',
				'Prompt' => '提示词',
				'Generate' => '生成',
				'Generating…' => '正在生成…',
				'RTL stylesheet "%1$s" is missing and will not be available.' => '缺少 RTL 样式表“%1$s”，因此不可用。',
				'Invalid response from image generation' => '图片生成返回无效响应',
				'An error occurred during image generation.' => '图片生成过程中发生错误。',
				'This feature requires an AI Connector that supports image generation. Review your Connectors to ensure you have a valid AI Connector configured.' => '此功能需要支持图片生成的 AI 连接器。请检查连接器，确保已配置有效的 AI 连接器。',
				'Save to Media Library' => '保存到媒体库',
				'Refine Image' => '优化图片',
				'Generate Another Image' => '再生成一张图片',
				'Start over' => '重新开始',
				'Describe the refinements you want to make to the image' => '描述你想对图片进行的优化',
				'Apply' => '应用',
				'Cancel' => '取消',
				'Saving to Media Library…' => '正在保存到媒体库…',
				'Failed to save image.' => '图片保存失败。',
				'Previous version' => '上一个版本',
				'Next version' => '下一个版本',
				'Use Image' => '使用图片',
				'Uploading image…' => '正在上传图片…',
				'Failed to upload image.' => '图片上传失败。',
				'Edit Prompt' => '编辑提示词',
				'%1$d / %2$d' => '%1$d / %2$d',
				'AI Generated Featured Image' => 'AI 生成的特色图片',
				'Brush size' => '画笔大小',
				'Cancel Refinement' => '取消优化',
				'Clear' => '清除',
				'Describe the refinements you want to make to the image.' => '描述你想对图片进行的优化。',
				'Describe what to replace with' => '描述要替换成什么',
				'Expand Background' => '扩展背景',
				'Failed to apply drawing to image.' => '应用绘制到图片失败。',
				'Failed to generate prompt: %s' => '生成提示词失败：%s',
				'Generate featured image' => '生成特色图片',
				'Generated by %1$s using %2$s on %3$s. Prompt: %4$s' => '由 %1$s 使用 %2$s 于 %3$s 生成。提示词：%4$s',
				'Generating image' => '正在生成图片',
				'Generating image prompt' => '正在生成图片提示词',
				'Image saved!' => '图片已保存！',
				'Image successfully added to the Media Library.' => '图片已成功添加到媒体库。',
				'Importing image…' => '正在导入图片…',
				'Invalid response from generate image.' => '生成图片返回无效响应。',
				'Invalid response from image generation.' => '图片生成返回无效响应。',
				'Invalid response from image import.' => '图片导入返回无效响应。',
				'Original image' => '原始图片',
				'Refine' => '优化',
				'Remove' => '移除',
				'Remove Background' => '移除背景',
				'Remove Item' => '移除项目',
				'Replace' => '替换',
				'Replace Item' => '替换项目',
				'Undo' => '撤销',
				'Uploading image to Media Library…' => '正在上传图片到媒体库…',
				'Version %d' => '版本 %d',
				'View in Media Library' => '在媒体库中查看',
				'View new image' => '查看新图片',
				'Total Abilities' => '能力总数',
				'Core' => '核心',
				'Plugins' => '插件',
				'Theme' => '主题',
				'All Providers' => '所有提供方',
				'All Categories' => '所有分类',
				'Filter by provider' => '按提供方筛选',
				'Filter by category' => '按分类筛选',
				'Filter' => '筛选',
				'Search Abilities' => '搜索能力',
				'Name' => '名称',
				'Slug' => '标识',
				'Provider' => '提供方',
				'Actions' => '操作',
				'Plugin' => '插件',
				'View' => '查看',
				'Test' => '测试',
				'Test Ability' => '测试能力',
				'Test Ability:' => '测试能力：',
				'View Details' => '查看详情',
				'&larr; Back to List' => '&larr; 返回列表',
				'No ability specified.' => '未指定能力。',
				'Ability not found.' => '未找到能力。',
				'Description' => '描述',
				'Details' => '详情',
				'Input Schema' => '输入 Schema',
				'Output Schema' => '输出 Schema',
				'Raw Data' => '原始数据',
				'Input Data' => '输入数据',
				'No Input Required' => '无需输入',
				'This ability does not accept any input parameters. Simply click "Invoke Ability" to execute it.' => '此能力不接受任何输入参数。直接点击“调用能力”即可执行。',
				'Edit the JSON input below to test the ability. The input will be validated against the input schema if available.' => '编辑下面的 JSON 输入来测试此能力。如果存在输入 schema，系统会按 schema 进行验证。',
				'How to test:' => '如何测试：',
				'Edit the JSON input below with your test data' => '用你的测试数据编辑下面的 JSON 输入',
				'Click "Validate Input" to check your JSON is correct' => '点击“验证输入”检查 JSON 是否正确',
				'Click "Invoke Ability" to execute the ability with your input' => '点击“调用能力”，使用当前输入执行此能力',
				'View the results below' => '在下方查看结果',
				'Ability test input (JSON)' => '能力测试输入（JSON）',
				'Invoke Ability' => '调用能力',
				'Validate Input' => '验证输入',
				'Clear Result' => '清除结果',
				'Result' => '结果',
				'Input Schema Reference' => '输入 Schema 参考',
				'Copy' => '复制',
				'Invoking ability...' => '正在调用能力...',
				'Success!' => '成功！',
				'Error' => '错误',
				'Invalid JSON input' => '无效的 JSON 输入',
				'Are you sure you want to invoke this ability?' => '确定要调用此能力吗？',
				'Copied!' => '已复制！',
				'Failed to copy' => '复制失败',
				'Valid' => '有效',
				'Validation Errors' => '验证错误',
				'JSON syntax is valid' => 'JSON 语法有效',
				'Failed to parse input schema' => '无法解析输入 schema',
				'Input is valid according to the schema' => '输入符合 schema 要求',
				'Input validation failed.' => '输入验证失败。',
				'Ability invoked successfully.' => '能力调用成功。',
				'Ability slug is required.' => '必须提供能力标识。',
				'Insufficient permissions.' => '权限不足。',
				'Unknown error occurred.' => '发生未知错误。',
				'Overview' => '概览',
				'Providers' => '提供方',
				'Testing' => '测试',
				'For more information:' => '更多信息：',
				'Abilities API Documentation' => 'Abilities API 文档',
				'You can test any ability directly from this screen:' => '你可以直接在此页面测试任意能力：',
				'Click "Test" next to an ability in the list.' => '点击列表中某个能力旁边的“测试”。',
				'Edit the pre-filled Input Data if the ability accepts JSON parameters.' => '如果该能力接受 JSON 参数，可以编辑预填的输入数据。',
				'Use "Validate Input" to check your JSON against the schema.' => '使用“验证输入”按 schema 检查 JSON。',
				'Click "Invoke Ability" to execute it and see the result.' => '点击“调用能力”执行并查看结果。',
			);
		}
	}
}
